// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Answer struct {
	ID         int32        `json:"id"`
	Answer     string       `json:"answer"`
	QuestionID int32        `json:"question_id"`
	UserID     int32        `json:"user_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type MagicLink struct {
	ID        int32        `json:"id"`
	Token     string       `json:"token"`
	Email     string       `json:"email"`
	ExpiresAt time.Time    `json:"expires_at"`
	Used      sql.NullBool `json:"used"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Question struct {
	ID        int32          `json:"id"`
	Content   sql.NullString `json:"content"`
	UserID    int32          `json:"user_id"`
	CreatedAt sql.NullTime   `json:"created_at"`
	LikeCount sql.NullInt32  `json:"like_count"`
}

type Room struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	OwnerID   int32        `json:"owner_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
	Name      string       `json:"name"`
	Role      string       `json:"role"`
}
