// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID         int32            `json:"id"`
	Answer     string           `json:"answer"`
	QuestionID int32            `json:"question_id"`
	UserID     int32            `json:"user_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type MagicLink struct {
	ID        int32            `json:"id"`
	Token     string           `json:"token"`
	Email     string           `json:"email"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Used      pgtype.Bool      `json:"used"`
	UsedAt    pgtype.Timestamp `json:"used_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Question struct {
	ID         int32            `json:"id"`
	Content    string           `json:"content"`
	UserID     int32            `json:"user_id"`
	LikeCount  pgtype.Int4      `json:"like_count"`
	IsAnswered pgtype.Bool      `json:"is_answered"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Room struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	OwnerID   int32            `json:"owner_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Email     string           `json:"email"`
	Name      string           `json:"name"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
